### ISSUE TITLE
Continue Work?

### ISSUE THREAD

**Issue by dav-is** [DSchau/transmission-web-interface#9]
Maybe you could continue work on this?

**Comment by DSchau** [comment]
Hi!

I was running into insoluble performance problems, and kind of just hit a wall with that, and other, concerns.

You're welcome to fork and it and continue work, I would love nothing more! I did also start on a [react version here](https://github.com/DSchau/transmission-ui), but I'm uncertain if I'll finish that either 😞

**Comment by dav-is** [comment]
Maybe try mithril? It's pretty preformant. I'm too busy to work on something like this. I just was looking for a nicer theme to transmission. Thanks for the speedy responce!

**Comment by DSchau** [comment]
No problem! I'll let you know if I ever continue work on it, I've been wanting to re-design Transmission Web UI for years now... ! Thanks for the interest!
